var Aristos = [ {Id:1, Name:"Mushashi", Image:"mushashi.png"},
{Id:2, Name:"Wild Bill", Image:"wild_bill.png"},
{Id:3, Name:"Gata", Image:"gata.png"},
{Id:4, Name:"Major Lunah", Image:"lunah.png"},
{Id:5, Name:"Hexx3r", Image:"hexx3r.png"},
{Id:6, Name:"Parvati", Image:"parvati.png"},
{Id:7, Name:"8-Ball", Image:"8ball.png"},
{Id:8, Name:"Maximus", Image:"maximus.png"},
{Id:9, Name:"Valkyrie", Image:"valkyrie.png"},
{Id:10, Name:"Hannibal", Image:"hannibal.png"},
{Id:11, Name:"Laxmee", Image:"laxmee.png"},
{Id:12, Name:"Señor Massacre", Image:"massacre.png"},
{Id:13, Name:"Padre Mendoza", Image:"mendoza.png"},
{Id:14, Name:"Murtair", Image:"murtair.png"},
{Id:15, Name:"Kozmo", Image:"kozmo.png"},
{Id:16, Name:"Taowu", Image:"taowu.png"},
{Id:17, Name:"Dart", Image:"dart.png"},
{Id:18, Name:"Bixie", Image:"bixie.png"},
{Id:19, Name:"Prysm", Image:"prysm.png"},
{Id:20, Name:"Eclypse", Image:"eclypse.png"},
{Id:21, Name:"Oberon", Image:"oberon.png"},
{Id:22, Name:"Shona Carano", Image:"shona.png"},
{Id:23, Name:"Reina Koorie", Image:"koorie.png"},
{Id:24, Name:"Final Boss", Image:"boss.png"} ,
{Id:25, Name:"Bachmann", Image:"bachmann.png"} ,
{Id:26, Name:"Hammerhead", Image:"hammerhead.png"} ,];

